export const DIALOGUES_DATA = [
  {
    name: "	Reliance Industries Ltd.",
    kind: "Messenger",
    brand: "HRA",
    id: 0,
  },
  {
    name: "	A&M Records.",
    kind: "Messenger",
    brand: "HRA",
    id: 1,
  },
  {
    name: "	Abba Seafood",
    kind: "Messenger",
    brand: "HRA",
    id: 2,
  },
  {
    name: "	3dfx Interactive.",
    kind: "Messenger",
    brand: "HRA",
    id: 3,
  },
  {
    name: "A&W Root Beer	",
    kind: "Messenger",
    brand: "HRA",
    id: 4,
  },
  {
    name: "	BRAC",
    kind: "Messenger",
    brand: "HRA",
    id: 5,
  },
  {
    name: "	Bridgestone",
    kind: "Messenger",
    brand: "HRA",
    id: 6,
  },
  {
    name: "	Brine",
    kind: "Messenger",
    brand: "HRA",
    id: 7,
  },
  {
    name: "	Brooks Sports",
    kind: "Messenger",
    brand: "HRA",
    id: 8,
  },
  {
    name: "Brunswick Corporation	",
    kind: "Messenger",
    brand: "HRA",
    id: 9,
  },
  {
    name: "	Cadillac",
    kind: "Messenger",
    brand: "HRA",
    id: 10,
  },
  {
    name: "CAE	",
    kind: "Messenger",
    brand: "HRA",
    id: 11,
  },
  {
    name: "Campagnolo	",
    kind: "Messenger",
    brand: "HRA",
    id: 12,
  },
  {
    name: "	Canon",
    kind: "Messenger",
    brand: "HRA",
    id: 13,
  },
  {
    name: "Capcom	",
    kind: "Messenger",
    brand: "HRA",
    id: 14,
  },
  {
    name: "Caprabo	",
    kind: "Messenger",
    brand: "HRA",
    id: 15,
  },
  {
    name: "	Carrefour",
    kind: "Messenger",
    brand: "HRA",
    id: 16,
  },
  {
    name: "Casio	",
    kind: "Messenger",
    brand: "HRA",
    id: 17,
  },
  {
    name: "	DEKA",
    kind: "Messenger",
    brand: "HRA",
    id: 18,
  },
  {
    name: "Delhaize	",
    kind: "Messenger",
    brand: "HRA",
    id: 19,
  },
  {
    name: "Dell	",
    kind: "Messenger",
    brand: "HRA",
    id: 20,
  },
  {
    name: "	DFI",
    kind: "Messenger",
    brand: "HRA",
    id: 21,
  },
  {
    name: "	DHL",
    kind: "Messenger",
    brand: "HRA",
    id: 22,
  },
  {
    name: "	Diageo",
    kind: "Messenger",
    brand: "HRA",
    id: 23,
  },
  {
    name: "EMI	",
    kind: "Messenger",
    brand: "HRA",
    id: 24,
  },
  {
    name: "	Emporis",
    kind: "Messenger",
    brand: "HRA",
    id: 25,
  },
  {
    name: "	Epson",
    kind: "Messenger",
    brand: "HRA",
    id: 26,
  },
  {
    name: "	Equifax",
    kind: "Messenger",
    brand: "HRA",
    id: 27,
  },
  {
    name: "	Ericsson",
    kind: "Messenger",
    brand: "HRA",
    id: 28,
  },
  {
    name: "	Ernst & Young",
    kind: "Messenger",
    brand: "HRA",
    id: 29,
  },
  {
    name: "	ESPN",
    kind: "Messenger",
    brand: "HRA",
    id: 30,
  },
  {
    name: "	ESRI",
    kind: "Messenger",
    brand: "HRA",
    id: 31,
  },
  {
    name: "	Esso",
    kind: "Messenger",
    brand: "HRA",
    id: 32,
  },
  {
    name: "	Etsy",
    kind: "Messenger",
    brand: "HRA",
    id: 33,
  },
  {
    name: "	Euronext",
    kind: "Messenger",
    brand: "HRA",
    id: 34,
  },
  {
    name: "	Evernote",
    kind: "Messenger",
    brand: "HRA",
    id: 35,
  },
  {
    name: "Exidy	",
    kind: "Messenger",
    brand: "HRA",
    id: 36,
  },
  {
    name: "Exxon	",
    kind: "Messenger",
    brand: "HRA",
    id: 37,
  },
  {
    name: "	FedEx",
    kind: "Messenger",
    brand: "HRA",
    id: 38,
  },
  {
    name: "FEGIME	",
    kind: "Messenger",
    brand: "HRA",
    id: 39,
  },
  {
    name: "	Ferodo",
    kind: "Messenger",
    brand: "HRA",
    id: 40,
  },
  {
    name: "	Ferrari",
    kind: "Messenger",
    brand: "HRA",
    id: 41,
  },
  {
    name: "	Fever-Tree",
    kind: "Messenger",
    brand: "HRA",
    id: 42,
  },
  {
    name: "	Fiat ",
    kind: "Messenger",
    brand: "HRA",
    id: 43,
  },
  {
    name: "	Komatsu",
    kind: "Messenger",
    brand: "HRA",
    id: 44,
  },
  {
    name: "Kone	",
    kind: "Messenger",
    brand: "HRA",
    id: 45,
  },
  {
    name: "	Konica",
    kind: "Messenger",
    brand: "HRA",
    id: 46,
  },
  {
    name: "	Korg",
    kind: "Messenger",
    brand: "HRA",
    id: 47,
  },
  {
    name: "	KPMG",
    kind: "Messenger",
    brand: "HRA",
    id: 48,
  },
  {
    name: "Maggi	",
    kind: "Messenger",
    brand: "HRA",
    id: 49,
  },
  {
    name: "	Mandriva",
    kind: "Messenger",
    brand: "HRA",
    id: 50,
  },
];
